--- dependencies of configs
--- @return LazySpec
return {
    require 'plugin.require.ui.colortheme.catppuccin',
    -- require 'plugin.require.language.language_tool.coc',
    require 'plugin.require.ui.nvim_tree',
	require 'plugin.require.ui.indent_blankline',
	require 'plugin.require.tool.vcs.git.gitsigns',
    'mfussenegger/nvim-dap',
    'sbdchd/neoformat',
    'jiangmiao/auto-pairs',
	require 'plugin.require.editor.nvim_surround',
    'theHamsta/nvim-dap-virtual-text',
    require 'plugin.require.language.languages.rust.rustaceanvim',
	require 'plugin.require.editor.which_key',
	require 'plugin.require.tool.vcs.git.lazygit',
    'voldikss/vim-floaterm',
    'rafcamlet/nvim-luapad',
    require 'plugin.require.tool.markdown_preview',
	require 'plugin.require.language.languages.lua.lazydev',
    require 'plugin.require.language.language_tool.nvim_cmp',
    require 'plugin.require.ui.dashboard',
	{
		'mg979/vim-visual-multi',
	},
    'neovim/nvim-lspconfig',
    -- 'dyng/ctrlsf.vim',
    require 'plugin.require.tool.navigator',
    -- require 'plugin.require.ui.dressing_nvim',
    {
        'rcarriga/nvim-dap-ui',
        dependencies = { 'mfussenegger/nvim-dap', 'nvim-neotest/nvim-nio' }
    },
    'williamboman/mason.nvim',
    'williamboman/mason-lspconfig.nvim',
	'hrsh7th/vim-vsnip-integ',
	'jbyuki/one-small-step-for-vimkind',
    'hrsh7th/cmp-cmdline',
    require 'plugin.require.tool.ai.fittencode',
	require 'plugin.require.ui.lualine',
	require 'plugin.require.ui.bufferline',
    require 'plugin.require.language.language_tool.nvim_treesitter',
	'HiPhish/rainbow-delimiters.nvim',
	require 'plugin.require.language.language_tool.refactoring',
	require 'plugin.require.tool.telescope',
	require 'plugin.require.tool.nvim_rip_substitute',
	require 'plugin.require.tool.grugfar',
	require 'plugin.require.tool.outline',
	require 'plugin.require.language.language_tool.playground',
	require 'plugin.require.editor.nvim_ufo',
	require 'plugin.require.ui.nvim_navic',
	require 'plugin.require.ui.nvim_treesitter_contest',
	require 'plugin.require.ui.noise_nvim',
	require 'plugin.require.editor.trouble',
	require 'plugin.require.tool.hydra',
	require 'plugin.require.language.toolchain.debug.mason_nvim_dap',
	require 'plugin.require.tool.im-select',
	-- require 'plugin.require.tool.ai.avante',
--------others
	require 'plugin.require.tool.firenvim',
	'MunifTanjim/nui.nvim',
}
