--- dependencies of configs

return {
    require 'plugin.require.ui.colortheme.catppuccin',
    require 'plugin.require.language.language_tool.coc',
    require 'plugin.require.ui.nvim_tree',
	require 'plugin.require.ui.indent_blankline',
	require 'plugin.require.tool.vcs.git.gitsigns',
    require 'plugin.require.language.language_tool.nvim_dap',
    require 'plugin.require.tool.neo_format',
    require 'plugin.require.editor.auto_pairs',
	require 'plugin.require.editor.nvim_surround',
    require 'plugin.require.ui.nvim_dap_virtual_text',
    require 'plugin.require.language.language_require.rust.rustaceanvim',
	-- require 'plugin.require.language.language_require.lua.lazydev',
	require 'plugin.require.editor.which_key',
	require 'plugin.require.tool.vcs.git.lazygit',
    require 'plugin.require.tool.floaterm',
    require 'plugin.require.tool.luapad',
    require 'plugin.require.tool.markdown_preview',
    require 'plugin.require.language.language_tool.nvim_cmp',
    require 'plugin.require.ui.dashboard',
	require 'plugin.require.tool.visual_multi',
    require 'plugin.require.language.language_tool.lsp_cfg',
    require 'plugin.require.tool.navigator',
    require 'plugin.require.ui.dressing_nvim',
    require 'plugin.require.language.language_tool.nvim_dap_ui',
    require 'plugin.require.language.language_tool.mason',
    require 'plugin.require.language.language_tool.mason_lspconfig',
	require 'plugin.require.language.language_tool.mason_nvim_dap',
    require 'plugin.require.language.language_tool.cmp_cmdline',
    require 'plugin.require.tool.ai.fittencode',
	require 'plugin.require.ui.lualine',
	require 'plugin.require.ui.bufferline',
    require 'plugin.require.language.language_tool.nvim_treesitter',
	require 'plugin.require.editor.rainbow_delimiters',
	require 'plugin.require.language.language_tool.refactoring',
	require 'plugin.require.tool.telescope',
	require 'plugin.require.tool.nvim_rip_substitute',
	require 'plugin.require.tool.grugfar',
	require 'plugin.require.tool.outline',
	require 'plugin.require.language.language_tool.playground',
	require 'plugin.require.editor.nvim_ufo',
	require 'plugin.require.ui.nvim_navic',
	require 'plugin.require.ui.nvim_treesitter_contest',
	require 'plugin.require.ui.noise_nvim',
	require 'plugin.require.editor.trouble',
	require 'plugin.require.tool.hydra',
	require 'plugin.require.tool.im-select',
	require 'plugin.require.tool.ai.avante',
	require 'plugin.require.editor.project_dir_cfg',
	require 'plugin.require.language.language_tool.ostf_vimkind',
	require 'plugin.require.editor.render_markdown',
	require 'plugin.require.ui.nvim_highight_colors',
	require 'plugin.require.ui.vim_illuminate',
	require 'plugin.require.editor.todo_comments',
	-- require 'plugin.require.editor.rime_nvim',
	-- require 'plugin.require.language.language_tool.cmp_rime',
	require 'plugin.require.language.language_tool.lsp-signature',
	-- require 'plugin.require.ui.telescope_select_ui',
	require 'plugin.require.tool.telescope_fzf',
	require 'plugin.require.language.language_require.haskell.haskell_tool',
	require 'plugin.require.language.language_tool.nvim_test',
	require 'plugin.require.tool.undotree',
    require 'plugin.require.editor.mininvim',
    -- require 'plugin.require.editor.orgmode',
    -- require 'plugin.require.editor.neorg',
    require 'plugin.require.tool.yazi',
    -- require 'plugin.require.ui.neoscrool',
    require 'plugin.require.ui.flash',
    require 'plugin.require.ui.smear-cursor',
    require 'plugin.require.ui.vim-smoothie',
    require 'plugin.require.language.language_require.sonicpi',
    require 'plugin.require.tool.carbon-now',
    require 'plugin.require.tool.snacks',
    require 'plugin.require.ui.neotree',
    require 'plugin.require.ui.edgy',
    require 'plugin.require.ui.codewindow',
    -- require 'plugin.require.language.language_require.csharp',
    require 'plugin.require.tool.mcp',

--------others
	require 'plugin.require.tool.firenvim',
}
